name: malison
version: 0.11.0
author: Bob Nystrom <robert@stuffwithstuff.com>
description: A little terminal UI package for the browser.
homepage: https://github.com/munificent/malison
dependencies:
  piecemeal: ">=0.3.7 <0.5.0"
dev_dependencies:
  build_runner: any
  build_web_compilers: any
environment:
  sdk: "^2.0.0"
