name: malison
version: 0.10.1
author: Bob Nystrom <robert@stuffwithstuff.com>
description: A little terminal UI package for the browser.
homepage: https://github.com/munificent/malison
dependencies:
  piecemeal: "^0.3.7"
dev_dependencies:
  browser: any
  build_runner: any
  build_web_compilers: any
environment:
  sdk: ">=2.0.0-dev.62.0 <3.0.0"
