name: malison
version: 0.13.1
description: A little terminal UI package for the browser.
homepage: https://github.com/munificent/malison
dependencies:
  piecemeal: "^2.0.0"
dev_dependencies:
  build_runner: any
  build_web_compilers: any
  lints: "^2.1.1"
environment:
  sdk: "^3.5.0"
